#!/usr/bin/env python3

import getopt
import sys

help_message = """
fetch-latest-libraries -o <download_location> -t <github_api_token> -c <circuitpython_version>

Options:
  - -o --output-dir\t\t\tthe directory to download the libraries from
  - -t --github-token\t\t\tthe token to use to download the files
  - -c --circuitpython-verison\t\tthe version of the libraries to download, for example 7.x or 8.x
"""


def print_mini_help_and_exit():
    print("fetch-latest-libraries -o <download_location> -t <github_api_token>")
    sys.exit(2)


def main(argv):
    output_dir = ""
    github_token = ""
    circuitpython_version = ""

    try:
        opts, args = getopt.getopt(
            argv, "ho:t:c:", [
                "help", "output-dir=", "github-token=", "circuitpython-version="
            ]
        )
    except getopt.GetoptError:
        print_mini_help_and_exit()

    for opt, arg in opts:
        if opt in ("-h", "--help"):
            print(help_message)
            sys.exit()
        elif opt in ("-o", "--output-dir"):
            output_dir = arg
        elif opt in ("-t", "--github-token"):
            github_token = arg
        elif opt in ("-c", "--circuitpython-version"):
            circuitpython_version = arg

    if len(output_dir) == 0 or len(github_token) == 0 or len(circuitpython_version) == 0:
        print_mini_help_and_exit()


if __name__ == "__main__":
    main(sys.argv[1:])
